config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'

  resources :restaurants, only: [:new, :create, :index, :show] do
    resources :reviews, only: [:new, :create]
  end

  namespace :admin do
    resources :restaurants, only: [:update, :edit, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ['chinese', 'italian', 'japanese', 'french', 'belgian'] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, inclusion: { in: (0..5) }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
   before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
    # @review = Review.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
    @restaurant.save
  end

  def update
    @restaurant.update(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


  def new
    # we need @restaurant in our `simple_form_for`
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    if @review.save
      redirect_to restaurant_path(@review.restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating, :restaurant_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="container">
  <div class="form-group">
    <%= simple_form_for @restaurant do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :phone_number %>
      <%= f.input :category, collection: ['chinese', 'japanese', 'french', 'belgian', 'italian'] %>
      <%= f.submit "Validate", class: "btn btn-primary" %>
    <% end %>
    <hr>
    <%= link_to "Back to the list", restaurants_path, class: "btn btn-primary"%>
  </div>
</div>

app/views/restaurants/edit.html.erb
<div class="container">
  <h2 class="text-center">Update the restaurant</h2>
  <%= render 'form', restaurant: @restaurant %>

</div>

app/views/restaurants/index.html.erb
<div class="container text-center">
  <%= link_to "Add a new restaurant", new_restaurant_path %>

  <% @restaurants.each do |restaurant|%>
  <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
  <p><%= restaurant.name %></p>
  <p><%= restaurant.address %></p>
  <p><%= restaurant.phone_number %></p>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1 class="text-center">New restaurant</h1>

  <%= render 'form'%>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="text-center">
    <h2><%= @restaurant.name %></h2>
    <hr>
    <h3><%= @restaurant.address %></h3>
    <h3><%= @restaurant.category %></h3>
    <ul class="list-unstyled">
      <% @restaurant.reviews.each do |review| %>
      <li>
       Message : <%= review.content %> / Rating : <%= review.rating %>
      </li>

    <% end %>
    </ul>
    <hr>
    <%= render 'reviews/form'%>
    <hr>
  </div>
  <%= link_to "Back to the list", restaurants_path, class: "btn btn-primary" %>
  <%= link_to "Edit", edit_admin_restaurant_path(@restaurant), class: "btn btn-primary" %>


</div>

app/views/reviews/_form.html.erb
<!-- charger la gem simple form -->

<div class="container">
  <%= simple_form_for [@restaurant, @review = Review.new] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "add a review", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "add a review", class: "btn btn-primary" %>
  <% end %>
</div>